packages:
  - .

overrides:
  'form-data@<4.0.4': '^4.0.4'
  'fast-xml-parser@<5.3.5': '^5.3.5'
  'glob@>=10.2.0 <10.5.0': '^10.5.0'
  'tmp@<0.2.4': '^0.2.4'

allowBuilds:
  '@tailwindcss/oxide': true
  core-js: false
  cpu-features: false
  esbuild: false
  osx-temperature-sensor: true
  protobufjs: false
  sharp: true
  ssh2: false

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - osx-temperature-sensor
  - protobufjs
  - sharp
